# The name of your app on Fly.io — VERY important
app = "the-wave-clothes"

# (Optional) Set your default region
primary_region = "jnb"

# Environment variable Fly uses to expose the app
[env]
PORT = "8080"

# Tell Fly which port to expose and how to serve it
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443